### ISSUE TITLE
Sonarqube: force authentication

### ISSUE THREAD

**Issue by emuthiah** [BCDevOps/sonarqube#24]
The default setting for authentication is disabled in sonarqube. This allows anonymous users access sonarqube and view pretty much everything including source code. This is not an issue for code in public repos, however it could be an issue if private code repos are used. 

Sonarqube setting:
/admin/settings?category=security
![image](https://user-images.githubusercontent.com/27945971/79485609-600ff000-7fca-11ea-8375-3f8e2cb2f929.png)
This can be addressed by setting environment variable `SONAR_FORCEAUTHENTICATION=true`

**Comment by emuthiah** [comment]
Pull request: https://github.com/BCDevOps/sonarqube/pull/25

**Comment by WadeBarnes** [comment]
Pull request merged.
